//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	provisionrequest "github.com/kubernetescode-aaserver/pkg/apis/provisionrequest"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ProvisionRequest)(nil), (*provisionrequest.ProvisionRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProvisionRequest_To_provisionrequest_ProvisionRequest(a.(*ProvisionRequest), b.(*provisionrequest.ProvisionRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*provisionrequest.ProvisionRequest)(nil), (*ProvisionRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_provisionrequest_ProvisionRequest_To_v1alpha1_ProvisionRequest(a.(*provisionrequest.ProvisionRequest), b.(*ProvisionRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProvisionRequestList)(nil), (*provisionrequest.ProvisionRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProvisionRequestList_To_provisionrequest_ProvisionRequestList(a.(*ProvisionRequestList), b.(*provisionrequest.ProvisionRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*provisionrequest.ProvisionRequestList)(nil), (*ProvisionRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_provisionrequest_ProvisionRequestList_To_v1alpha1_ProvisionRequestList(a.(*provisionrequest.ProvisionRequestList), b.(*ProvisionRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProvisionRequestSpec)(nil), (*provisionrequest.ProvisionRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProvisionRequestSpec_To_provisionrequest_ProvisionRequestSpec(a.(*ProvisionRequestSpec), b.(*provisionrequest.ProvisionRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*provisionrequest.ProvisionRequestSpec)(nil), (*ProvisionRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_provisionrequest_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec(a.(*provisionrequest.ProvisionRequestSpec), b.(*ProvisionRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProvisionRequestStatus)(nil), (*provisionrequest.ProvisionRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProvisionRequestStatus_To_provisionrequest_ProvisionRequestStatus(a.(*ProvisionRequestStatus), b.(*provisionrequest.ProvisionRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*provisionrequest.ProvisionRequestStatus)(nil), (*ProvisionRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_provisionrequest_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus(a.(*provisionrequest.ProvisionRequestStatus), b.(*ProvisionRequestStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ProvisionRequest_To_provisionrequest_ProvisionRequest(in *ProvisionRequest, out *provisionrequest.ProvisionRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProvisionRequestSpec_To_provisionrequest_ProvisionRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ProvisionRequestStatus_To_provisionrequest_ProvisionRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ProvisionRequest_To_provisionrequest_ProvisionRequest is an autogenerated conversion function.
func Convert_v1alpha1_ProvisionRequest_To_provisionrequest_ProvisionRequest(in *ProvisionRequest, out *provisionrequest.ProvisionRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProvisionRequest_To_provisionrequest_ProvisionRequest(in, out, s)
}

func autoConvert_provisionrequest_ProvisionRequest_To_v1alpha1_ProvisionRequest(in *provisionrequest.ProvisionRequest, out *ProvisionRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_provisionrequest_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_provisionrequest_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_provisionrequest_ProvisionRequest_To_v1alpha1_ProvisionRequest is an autogenerated conversion function.
func Convert_provisionrequest_ProvisionRequest_To_v1alpha1_ProvisionRequest(in *provisionrequest.ProvisionRequest, out *ProvisionRequest, s conversion.Scope) error {
	return autoConvert_provisionrequest_ProvisionRequest_To_v1alpha1_ProvisionRequest(in, out, s)
}

func autoConvert_v1alpha1_ProvisionRequestList_To_provisionrequest_ProvisionRequestList(in *ProvisionRequestList, out *provisionrequest.ProvisionRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]provisionrequest.ProvisionRequest)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ProvisionRequestList_To_provisionrequest_ProvisionRequestList is an autogenerated conversion function.
func Convert_v1alpha1_ProvisionRequestList_To_provisionrequest_ProvisionRequestList(in *ProvisionRequestList, out *provisionrequest.ProvisionRequestList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProvisionRequestList_To_provisionrequest_ProvisionRequestList(in, out, s)
}

func autoConvert_provisionrequest_ProvisionRequestList_To_v1alpha1_ProvisionRequestList(in *provisionrequest.ProvisionRequestList, out *ProvisionRequestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ProvisionRequest)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_provisionrequest_ProvisionRequestList_To_v1alpha1_ProvisionRequestList is an autogenerated conversion function.
func Convert_provisionrequest_ProvisionRequestList_To_v1alpha1_ProvisionRequestList(in *provisionrequest.ProvisionRequestList, out *ProvisionRequestList, s conversion.Scope) error {
	return autoConvert_provisionrequest_ProvisionRequestList_To_v1alpha1_ProvisionRequestList(in, out, s)
}

func autoConvert_v1alpha1_ProvisionRequestSpec_To_provisionrequest_ProvisionRequestSpec(in *ProvisionRequestSpec, out *provisionrequest.ProvisionRequestSpec, s conversion.Scope) error {
	out.IngressEntrance = in.IngressEntrance
	out.BusinessDbVolume = provisionrequest.DbVolume(in.BusinessDbVolume)
	out.NamespaceName = in.NamespaceName
	return nil
}

// Convert_v1alpha1_ProvisionRequestSpec_To_provisionrequest_ProvisionRequestSpec is an autogenerated conversion function.
func Convert_v1alpha1_ProvisionRequestSpec_To_provisionrequest_ProvisionRequestSpec(in *ProvisionRequestSpec, out *provisionrequest.ProvisionRequestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProvisionRequestSpec_To_provisionrequest_ProvisionRequestSpec(in, out, s)
}

func autoConvert_provisionrequest_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec(in *provisionrequest.ProvisionRequestSpec, out *ProvisionRequestSpec, s conversion.Scope) error {
	out.IngressEntrance = in.IngressEntrance
	out.BusinessDbVolume = DbVolume(in.BusinessDbVolume)
	out.NamespaceName = in.NamespaceName
	return nil
}

// Convert_provisionrequest_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec is an autogenerated conversion function.
func Convert_provisionrequest_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec(in *provisionrequest.ProvisionRequestSpec, out *ProvisionRequestSpec, s conversion.Scope) error {
	return autoConvert_provisionrequest_ProvisionRequestSpec_To_v1alpha1_ProvisionRequestSpec(in, out, s)
}

func autoConvert_v1alpha1_ProvisionRequestStatus_To_provisionrequest_ProvisionRequestStatus(in *ProvisionRequestStatus, out *provisionrequest.ProvisionRequestStatus, s conversion.Scope) error {
	out.IngressReady = in.IngressReady
	out.DbReady = in.DbReady
	return nil
}

// Convert_v1alpha1_ProvisionRequestStatus_To_provisionrequest_ProvisionRequestStatus is an autogenerated conversion function.
func Convert_v1alpha1_ProvisionRequestStatus_To_provisionrequest_ProvisionRequestStatus(in *ProvisionRequestStatus, out *provisionrequest.ProvisionRequestStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProvisionRequestStatus_To_provisionrequest_ProvisionRequestStatus(in, out, s)
}

func autoConvert_provisionrequest_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus(in *provisionrequest.ProvisionRequestStatus, out *ProvisionRequestStatus, s conversion.Scope) error {
	out.IngressReady = in.IngressReady
	out.DbReady = in.DbReady
	return nil
}

// Convert_provisionrequest_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus is an autogenerated conversion function.
func Convert_provisionrequest_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus(in *provisionrequest.ProvisionRequestStatus, out *ProvisionRequestStatus, s conversion.Scope) error {
	return autoConvert_provisionrequest_ProvisionRequestStatus_To_v1alpha1_ProvisionRequestStatus(in, out, s)
}
