apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aapiserver-clusterrole
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations","validatingwebhookconfigurations"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","watch","list","create","update","delete","patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list","create","delete","update","patch"]
- apiGroups: ["provision.mydomain.com"]
  resources: ["provisionrequests","provisionrequests/status"]
  verbs: ["get","watch","list","create", "update","patch"]
- apiGroups: ["flowcontrol.apiserver.k8s.io"]
  resources: ["prioritylevelconfigurations","flowschemas"]
  verbs: ["get","watch","list"]
- apiGroups: ["flowcontrol.apiserver.k8s.io"]
  resources: ["flowschemas/status"]
  verbs: ["get","watch","list","create", "update","patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aapiserver-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aapiserver-clusterrole
subjects:
- kind: ServiceAccount
  name: aapiserver
  namespace: kubernetescode-aapiserver

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aapiserver-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: aapiserver
  namespace: kubernetescode-aapiserver

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aapiserver-system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: aapiserver
  namespace: kubernetescode-aapiserver